name: CI | Deploy to DO Droplet
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: login, shutdown container, pull latest master and trigger fresh build
        uses: appleboy/ssh-action@master 
        with:
          host: ${{secrets.DO_HOST}}
          username: ${{secrets.DO_USERNAME}}
          password: ${{secrets.DO_PASSWORD}}
          script: |
            cd createYourBread-N-Breakfast
            #set all the env variables here
            set -o allexport; source ~/.env; set +o allexport
            #shut down all the containers:
            docker-compose down
            # remove all the dangling containers
            docker rmi $(docker images -f dangling=true -q)
            git checkout main
            git pull
            #rebuild from the existing app as and when required
            docker-compose up --build -d
            
        
      
  
